services:
    bff:
        build:
            context: ./bff
        ports:
            - "3000:3000"
        depends_on:
            - mf_drawer
            - mf_videos
        environment:
            - MF_DRAWER_URL=http://mf_drawer:80
            - MF_VIDEOS_URL=http://mf_videos:80

    mf_drawer:
        build:
            context: ./mf_drawer
        ports:
            - "8001:80"
        volumes:
            - ./mf_drawer:/usr/share/nginx/html
            - ./mf_drawer/nginx.conf:/etc/nginx/conf.d/default.conf

    mf_videos:
        build:
            context: ./mf_videos
        ports:
            - "8002:80"
        volumes:
            - ./mf_videos:/usr/share/nginx/html
            - ./mf_videos/nginx.conf:/etc/nginx/conf.d/default.conf

    front-end:
        build:
            context: ./front-end
        ports:
            - "3001:80"
        volumes:
            - ./front-end:/usr/share/nginx/html
            - ./front-end/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - bff
            - mf_drawer
            - mf_videos
